import Head from 'next/head'
import { Button, Checkbox, Form } from 'semantic-ui-react'
import styles from '../styles/Home.module.css'

export default function Login() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          ZallpyChat <a href="https://nextjs.org">Realtime!</a>
        </h1>

        <p className={styles.description}>
          Acesse o sistema por aqui:
        </p>
        <Form>
          <Form.Field>
            <label>Email</label>
            <input placeholder='digite seu E-mail' />
          </Form.Field>
          <Form.Field>
            <label>Senha</label>
            <input placeholder='digite sua senha' />
          </Form.Field>
          <Button primary className={styles.buttonPrimary} type='submit'>Entrar</Button>
        </Form>        
        </main>
    </div>
  )
}
